name: virtual-lab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - openmm
  - pdbfixer
  - mdtraj
  - rdkit
  - biopython
  - pandas
  - numpy
  - pyyaml
  - pytorch
  - torchvision
  - torchaudio
  - scikit-learn
  - faiss-cpu
  - tqdm
  - matplotlib
  - pip:
      - google-generativeai
      - langchain
      - langchain-huggingface
      - langchain-community
      - sentence-transformers
      - lucide-react
      - chromadb # Alternative to FAISS if needed
      - pydantic
